In [1]:
import requests
from IPython.core.display import HTML

# Bases and transformations
The following tasks are designed to provide a refresher on bases and transformations between them.

<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#basis">Task 1: Identifying Basis Vectors</a>
            </li>
            <li>
            <a href="#basis_combined">Task 2: Basis Transformation and Change of Coord…</a>
            </li>
            <li>
            <a href="#basis4">Task 3: Applying a Linear Transformation in Diff…</a>
            </li>
            <li>
            <a href="#basis5">Task 4: Basis and Dimensionality Check</a>
            </li>
        </ul>
    </div>
</article>


---
**Task 1 (easy): Identifying Basis Vectors♾️**
Given the following bases vectors for $\mathbb{R}^2$:

$$
\begin{array}{l}
1. \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\} \\[12pt]
2. \left\{ \begin{bmatrix} 2 \\ 3 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\} \\[12pt]
3. \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 2 \\ 2 \end{bmatrix} \right\} \\
\end{array}
$$
1. Which of these sets forms a basis for $\mathbb{R}^2 $? Justify your answer by checking linear independence and spanning the vector space.


---

In [2]:
import numpy as np

# Function to check if a set of vectors forms a basis by checking linear independence
def is_linearly_independent(vectors):
    matrix = np.column_stack(vectors)  # Form a matrix with vectors as columns
    rank = np.linalg.matrix_rank(matrix)
    return rank == len(vectors)  # True if rank equals the number of vectors

# Define the vector sets
vectors_set_1 = [np.array([1, 0]), np.array([0, 1])]
vectors_set_2 = [np.array([2, 3]), np.array([-1, 2])]
vectors_set_3 = [np.array([1, 1]), np.array([2, 2])]

# Check if each set is a basis
print("Set 1 forms a basis:", is_linearly_independent(vectors_set_1))
print("Set 2 forms a basis:", is_linearly_independent(vectors_set_2))
print("Set 3 forms a basis:", is_linearly_independent(vectors_set_3))

# Explanation
# For a set to form a basis for R^2, it must be linearly independent and span R^2.
# We checked linear independence using the matrix rank. If the rank equals the number of vectors, 
# they are linearly independent and thus form a basis if they are in R^2.

# Results:
# - Set 1: Standard basis vectors [1, 0] and [0, 1] are linearly independent.
# - Set 2: The vectors [2, 3] and [-1, 2] are linearly independent and span R^2.
# - Set 3: The vectors [1, 1] and [2, 2] are linearly dependent (rank is 1), so they do not form a basis.

Set 1 forms a basis: True
Set 2 forms a basis: True
Set 3 forms a basis: False



---
**Task 2 (hard): Basis Transformation and Change of Coordinates♾️**
Consider three bases in  $\mathbb{R}^2$:
1. The standard basis  
$$E = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\}$$
 
2. The basis  
$$B   = \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ -1 \end{bmatrix} \right\}$$
 
3. The basis  
$$C   = \left\{ \begin{bmatrix} 2 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ 3 \end{bmatrix} \right\}$$
 

Given two vectors in the standard basis:

$$
\text{v} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
\text{w} = \begin{bmatrix} 7 \\ 6 \end{bmatrix} 
$$
1. Draw the basis vectors for  $E$,  $B$ , and  $C$ and the vectors $\text{v}$ and $\text{w}$  on a piece of paper.

2. Express $\text{v}$ and $\text{w}$  in the basis  $B$. 

3. Express $\text{v}$  and $\text{w}$  in the basis $C$.

4. Find the change of basis matrix  $T_E^B$ that given a vector expressed in the basis  E  maps it to the basis B. 

5. Find the change of basis matrix  $T_E^C$ that given a vector expressed in the basis  E  maps it to the basis C.

6. Use the change of basis matrices to transform  $\text{v}$ and $\text{w}$ from standard basis to the basis $B$ and $C$ respectively. Verify that the resulting coordinates match your results from the previous steps.



---

In [3]:
standard_basis = np.array([[1, 0], [0, 1]])
basis_B = np.array([[1, 2], [2, -1]])
basis_C = np.array([[2, 1], [1, 3]])

# Given vectors in the standard basis
v = np.array([3, 1])
w = np.array([7, 6])

# Function to express a vector in a given basis
def change_coordinates(vector, basis):
    return np.linalg.solve(basis, vector)

# Express v and w in basis B
v_in_B = change_coordinates(v, basis_B)
w_in_B = change_coordinates(w, basis_B)
print("v in basis B:", v_in_B)
print("w in basis B:", w_in_B)

# Express v and w in basis C
v_in_C = change_coordinates(v, basis_C)
w_in_C = change_coordinates(w, basis_C)
print("v in basis C:", v_in_C)
print("w in basis C:", w_in_C)

# Find the change of basis matrices T_E^B and T_E^C
T_E_B = np.linalg.inv(basis_B)
T_E_C = np.linalg.inv(basis_C)
print("Change of basis matrix T_E^B:\n", T_E_B)
print("Change of basis matrix T_E^C:\n", T_E_C)

# Verify the transformations
v_transformed_B = T_E_B @ v
w_transformed_B = T_E_B @ w
v_transformed_C = T_E_C @ v
w_transformed_C = T_E_C @ w
print("v transformed to basis B:", v_transformed_B)
print("w transformed to basis B:", w_transformed_B)
print("v transformed to basis C:", v_transformed_C)
print("w transformed to basis C:", w_transformed_C)

# Explanation
# The results of transforming v and w using the change of basis matrices should match 
# the coordinates obtained earlier by solving the linear equations.

v in basis B: [1. 1.]
w in basis B: [3.8 1.6]
v in basis C: [ 1.6 -0.2]
w in basis C: [3. 1.]
Change of basis matrix T_E^B:
 [[ 0.2  0.4]
 [ 0.4 -0.2]]
Change of basis matrix T_E^C:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
v transformed to basis B: [1. 1.]
w transformed to basis B: [3.8 1.6]
v transformed to basis C: [ 1.6 -0.2]
w transformed to basis C: [3. 1.]



---
**Task 3 (easy): Applying a Linear Transformation in Different Bases♾️**
Let $ T: \mathbb{R}^2 \to \mathbb{R}^2 $ be a linear transformation represented by the matrix:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

in the standard basis. Let 

$$
B = \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\}
$$
 
be a new basis.
1. Calculate the matrix that represents $ T $ with respect to the basis $ B $. Use the change of basis matrices to show your work.


---

In [4]:
# Task 3: Applying a Linear Transformation in Different Bases
# Define the transformation matrix A in the standard basis
A = np.array([[1, 2], [3, 4]])

# Change of basis matrix from standard basis to basis B
P_B = np.column_stack([np.array([1, 1]), np.array([-1, 2])])  # Basis B as columns
P_B_inv = np.linalg.inv(P_B)

# Matrix representing T in basis B
A_B = P_B_inv @ A @ P_B
print("Transformation matrix A in basis B:\n", A_B)

# Explanation
# The matrix A_B represents the linear transformation T in the new basis B.

Transformation matrix A in basis B:
 [[4.33333333 3.66666667]
 [1.33333333 0.66666667]]



---
**Task 4 (easy): Basis and Dimensionality Check♾️**
Suppose $ \mathbb{R}^3 $ has a basis given by 

$$
B = \left\{ \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix} \right\}.
$$

1. Verify that $ B $ is a basis by showing it spans $ \mathbb{R}^3 $ and is linearly independent.
2. If a fourth vector $ \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix} $ is added to $ B $, does it still form a basis for $ \mathbb{R}^3 $? Explain your reasoning in terms of dimension.


---

In [5]:
# Task 4: Basis and Dimensionality Check
# Define the given basis for R^3
basis_R3 = [np.array([1, 0, 1]), np.array([0, 1, 1]), np.array([1, -1, 0])]

# Check if the basis spans R^3 and is linearly independent
print("Basis B for R^3 is linearly independent:", is_linearly_independent(basis_R3))

# Adding a fourth vector to the basis
additional_vector = np.array([2, -1, 3])
basis_with_additional = basis_R3 + [additional_vector]

# Check if the new set with the additional vector still forms a basis
print("Basis B with the additional vector is linearly independent:", is_linearly_independent(basis_with_additional))

# Explanation
# A basis for R^3 must have exactly 3 linearly independent vectors. Adding a fourth vector results in a set of 4 vectors,
# which cannot form a basis for R^3 because the dimension of the space is 3. The rank check confirms whether the set 
# remains independent, but if the rank is still 3, it means the fourth vector is dependent on the existing basis vectors.

Basis B for R^3 is linearly independent: False
Basis B with the additional vector is linearly independent: False
